language: node_js 
node_js:
  - "14.15.2"
services:
  - docker 

before_install:
  - docker build -t leux1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true leux1/docker-react npm run test 
  


