language: node_js 
node_js:
  - "14.15.2"
services:
  - docker 

before_install:
  - docker build -t leux1/docker-react -f Dockerfile.dev .

script:
  - docker run leux1/docker-react npm test -- --coverage
  - npm stop


